import argparse

def init_results():
    return {
        "number_timeouts"       : 0,
        "mean_runtime"          : 0.0,
        "mean_decisions"        : 0,
        "mean_conflicts"        : 0,
        "mean_learned_clauses"  : 0,
        "mean_propagations"     : 0,
    }

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Analyze the results generated by the CDCL SAT solver")
    ap.add_argument("path", help="Path to results .csv file")
    args = ap.parse_args()
    results_path = './results/' + args.path

    results = {
        "baseline": init_results(),
        "vsids":    init_results(),
    }

    num_tests = 0

    with open(results_path, "r") as f:
        for raw_line in f:
            num_tests += 1

            if num_tests == 1:
                continue

            line = raw_line.strip().split(",")

            file_name       = line[0]
            file_path       = line[1]
            heuristic       = line[2]
            status          = line[3]
            runtime         = line[4]
            decisions       = line[5]
            conflicts       = line[6]
            learned_clauses = line[7]
            propagations    = line[8]

            if status == "TIMEOUT":
                results[heuristic]["number_timeouts"] += 1
            results[heuristic]["mean_runtime"]          += float(runtime)
            results[heuristic]["mean_decisions"]        += int(decisions)
            results[heuristic]["mean_conflicts"]        += int(conflicts)
            results[heuristic]["mean_learned_clauses"]  += int(learned_clauses)
            results[heuristic]["mean_propagations"]     += int(propagations)

    num_tests = (num_tests - 1) // 2

    print(f"Analysis for {file_name.split('-')[0]}")
    print(f"Number of CNF formulas in benchmark: {num_tests}")
    print(f"Speedup from VSIDS: {results["baseline"]["mean_runtime"] / results["vsids"]["mean_runtime"]}")

    for heuristic in results.keys():
        results[heuristic]["mean_runtime"]          /= num_tests
        results[heuristic]["mean_decisions"]        /= num_tests
        results[heuristic]["mean_conflicts"]        /= num_tests
        results[heuristic]["mean_learned_clauses"]  /= num_tests
        results[heuristic]["mean_propagations"]     /= num_tests

        # Show analysis
        print("------------")
        print(heuristic)
        for key in results[heuristic].keys():
            print(f"  {key}: {results[heuristic][key]}")
        print("------------")